version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "typo3/*"
        update-types: ["version-update:semver-major"]
